=== liangxiuxiu/repo1/bjsjw/WebContent/WEB-INF/config/component.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT components (component*)>

<!ELEMENT component ((css|js)+,dependencies?)>
<!ATTLIST component id ID #REQUIRED>

<!ELEMENT css (#PCDATA)>
<!ATTLIST css browser CDATA #IMPLIED>

<!ELEMENT js (#PCDATA)>
<!ATTLIST js browser CDATA #IMPLIED>

<!ELEMENT dependencies (#PCDATA)>

=== liangxiuxiu/repo1/bjsjw/WebContent/WEB-INF/config/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components PUBLIC "-//www.hanweb.com//DTD Component Configuration 1.0//EN" "component.dtd">
<components>
	<component id="global">
		<css>/ui/css/global.css</css>
		<js>/ui/lib/jquery/jquery.min.js</js>
		<js>/ui/lib/jquery/jquery-migrate-1.4.1.min.js</js>
	</component>
	<component id="global-page">
		<js>/ui/script/ui.js</js>
		<css>/ui/css/page.css</css>
		<js>/ui/script/page.js</js>
		<dependencies>global,scrollup,cookie</dependencies>
	</component>
	<component id="global-dialog">
		<js>/ui/script/ui.js</js>
		<css>/ui/css/dialog.css</css>
		<js>/ui/script/dialog.js</js>
		<dependencies>global</dependencies>
	</component>
	<component id="resizable">
		<js>/ui/lib/easyui/plugins/jquery.resizable.js</js>
		<dependencies>parser</dependencies>
	</component>
	<component id="panel">
		<css>/ui/lib/easyui/themes/bootstrap/panel.css</css>
		<js>/ui/lib/easyui/plugins/jquery.panel.js</js>
		<dependencies>parser</dependencies>
	</component>
	<component id="draggable">
		<js>/ui/lib/easyui/plugins/jquery.draggable.js</js>
		<dependencies>parser</dependencies>
	</component>
	<component id="linkbutton">
		<css>/ui/lib/easyui/themes/bootstrap/linkbutton.css</css>
		<js>/ui/lib/easyui/plugins/jquery.linkbutton.js</js>
		<dependencies>parser</dependencies>
	</component>
	<component id="window">
		<css>/ui/lib/easyui/themes/bootstrap/window.css</css>
		<js>/ui/lib/easyui/plugins/jquery.window.js</js>
		<dependencies>parser,resizable,draggable,panel</dependencies>
	</component>
	<component id="pagination">
		<css>/ui/lib/easyui/themes/bootstrap/pagination.css</css>
		<js>/ui/lib/easyui/plugins/jquery.pagination.js</js>
		<dependencies>parser,linkbutton</dependencies>
	</component>
	<component id="layout">
		<css>/ui/lib/easyui/themes/bootstrap/layout.css</css>
		<js>/ui/lib/easyui/plugins/jquery.layout.js</js>
		<dependencies>parser,resizable,panel</dependencies>
	</component>
	<component id="message">
		<css>/ui/lib/easyui/themes/bootstrap/messager.css</css>
		<js>/ui/lib/easyui/plugins/jquery.messager.js</js>
		<dependencies>parser,linkbutton,window</dependencies>
	</component>
	<component id="tabs">
		<css>/ui/lib/easyui/themes/bootstrap/tabs.css</css>
		<js>/ui/lib/easyui/plugins/jquery.tabs.js</js>
		<dependencies>parser,panel,linkbutton</dependencies>
	</component>
	<component id="grid">
		<css>/ui/lib/easyui/themes/default/datagrid.css</css>
		<js>/ui/lib/easyui/plugins/jquery.datagrid.js</js>
		<css>/ui/widgets/hanweb/grid/css/grid.css</css>
		<js>/ui/widgets/hanweb/grid/grid.js</js>
		<dependencies>placeholder,parser,panel,resizable,pagination,iconfont</dependencies>
	</component>
	<component id="dialog">
		<css>/ui/lib/easyui/themes/bootstrap/dialog.css</css>
		<js>/ui/lib/easyui/plugins/jquery.dialog.js</js>
		<dependencies>parser,linkbutton,window</dependencies>
	</component>
	<component id="validity">
		<js>/ui/widgets/validity/validity.js</js>
		<css>/ui/widgets/hanweb/validity/css/validity.css</css>
		<js>/ui/widgets/hanweb/validity/validity.js</js>
	</component>
	<component id="calendar">
		<css>/ui/widgets/hanweb/calendar/css/calendar.css</css>
		<js>/ui/widgets/My97DatePicker/WdatePicker.js</js>
	</component>
	<component id="tree">
		<css>/ui/widgets/ztree/css/zTreeStyle/zTreeStyle.css</css>
		<js>/ui/widgets/ztree/js/jquery.ztree.all-3.5.min.js</js>
		<css>/ui/widgets/hanweb/tree/css/tree.css</css>
		<js>/ui/widgets/hanweb/tree/tree.js</js>
	</component>
	<component id="cookie">
		<js>/ui/widgets/cookie/jquery.cookie.js</js>
	</component>
	<component id="iconfont">
		<css>/ui/widgets/hanweb/iconfont/css/iconfont.css</css>
	</component>
	<component id="parser">
		<js>/ui/lib/easyui/plugins/jquery.parser.js</js>
		<dependencies>lang</dependencies>
	</component>
	<component id="lang">
		<js>/ui/widgets/hanweb/easyui/locale/easyui-lang-zh_CN.js</js>
	</component>
	<component id="scrollup">
		<css>/ui/widgets/scrollup/css/themes/image.css</css>
		<js>/ui/widgets/scrollup/js/jquery.scrollUp.min.js</js>
		<js>/ui/widgets/hanweb/ie6fixed/ie6fixed.js</js>
	</component>
	<component id="upload">
		<js>/ui/widgets/filestyle/jquery.filestyle.min.js</js>
		<css>/ui/widgets/hanweb/singlefileupload/css/filestyle.css</css>
		<js>/ui/widgets/hanweb/singlefileupload/singlefileupload.js</js>
	</component>
	<component id="multifileupload">
		<js>/ui/widgets/plupload/js/plupload.full.min.js</js>
		<css>/ui/widgets/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css</css>
		<js>/ui/widgets/plupload/js/jquery.plupload.queue/jquery.plupload.queue.js</js>
		<js>/ui/widgets/plupload/js/i18n/zh_CN.js</js>
		<js>/ui/widgets/hanweb/multifileupload/multifileupload.js</js>
		<css>/ui/widgets/hanweb/multifileupload/css/multifileupload.css</css>
		<dependencies>json,iconfont</dependencies>
	</component>
	<component id="cloudfile">
		<js>/ui/widgets/hanweb/fsupload/fileserver.js</js>
		<css>/ui/widgets/hanweb/fsupload/css/fileserver.css</css>
		<dependencies>multifileupload</dependencies>
	</component>
	<component id="cloudfile_image_clip">
		<js>/ui/widgets/hanweb/imgopr/imgareaselect/js/jquery.imgareaselect.js</js>
		<css>/ui/widgets/hanweb/imgopr/imgareaselect/css/imgareaselect-default.css</css>
		<js>/ui/widgets/hanweb/imgopr/jrotate/jQueryRotate.2.2.js</js>
		<js>/ui/widgets/hanweb/imgopr/slider/js/jquery.slider.min.js</js>
		<css>/ui/widgets/hanweb/imgopr/slider/css/jquery.slider.min.css</css>
		<js>/ui/widgets/hanweb/imgopr/drag/drag.js</js>
		<css>/ui/widgets/hanweb/imgopr/css/imgtools.css</css>
	</component>
	<component id="menu">
		<css>/ui/widgets/hanweb/menu/css/menu.css</css>
		<js>/ui/widgets/hanweb/menu/menu.js</js>
	</component>
	<component id="select">
		<css>/ui/widgets/hanweb/select/css/select.css</css>
		<js>/ui/widgets/hanweb/select/select.js</js>
		<dependencies>iconfont,menu</dependencies>
	</component>
	<component id="multiselect">
		<css>/ui/widgets/hanweb/multiselect/css/multiselect.css</css>
		<js>/ui/widgets/hanweb/multiselect/multiselect.js</js>
		<dependencies>iconfont,menu</dependencies>
	</component>
	<component id="loadmask">
		<js>/ui/widgets/loadmask/jquery.loadmask.min.js</js>
		<css>/ui/widgets/loadmask/jquery.loadmask.css</css>
	</component>
	<component id="tip">
		<js>/ui/widgets/poshytip/jquery.poshytip.min.js</js>
		<css>/ui/widgets/poshytip/tip-yellowsimple/tip-yellowsimple.css</css>
		<dependencies>iconfont</dependencies>
	</component>
	<component id="json">
		<js>/ui/widgets/json/json2.js</js>
	</component>
	<component id="checkpwd">
		<js>/ui/widgets/checkpwd/checkpwd.js</js>
		<css>/ui/widgets/checkpwd/css/checkpwd.css</css>
	</component>
	<component id="highlighter">
		<js>/ui/widgets/highlighter/scripts/brush.js</js>
		<css>/ui/widgets/highlighter/styles/shCore.css</css>
		<css>/ui/widgets/highlighter/styles/shThemeDefault.css</css>
	</component>
	<component id="editor">
		<js>/ui/widgets/ueditor/ueditor.config.js</js>
		<js>/ui/widgets/ueditor/ueditor.all.js</js>
	</component>
	<component id="toggle">
		<css>/ui/widgets/hanweb/toggle/css/toggle.css</css>
		<js>/ui/widgets/hanweb/toggle/toggle.js</js>
	</component>
	<component id="ipass">
		<js>/ui/widgets/iPass/iPass.min.js</js>
	</component>
	<component id="accordion">
		<css>/ui/lib/easyui/themes/bootstrap/accordion.css</css>
		<js>/ui/lib/easyui/plugins/jquery.accordion.js</js>
		<dependencies>parser,panel</dependencies>
	</component>
	<component id="security">
		<js>/ui/lib/security/jsencrypt.min.js</js>
		<js>/ui/lib/security/rsa_util.js</js>
	</component>
	<component id="codeedit">
		<js>/ui/widgets/codemirror/lib/jquery.codemirror.js</js>
		<js>/ui/widgets/codemirror/lib/codemirror.js</js>
		<css>/ui/widgets/codemirror/lib/codemirror.css</css>
		<js>/ui/widgets/codemirror/mode/xml/xml.js</js>
		<js>/ui/widgets/codemirror/mode/javascript/javascript.js</js>
		<js>/ui/widgets/codemirror/mode/css/css.js</js>
		<js>/ui/widgets/codemirror/mode/htmlmixed/htmlmixed.js</js>
		<js>/ui/widgets/codemirror/addon/hint/show-hint.js</js>
		<js>/ui/widgets/codemirror/addon/hint/css-hint.js</js>
		<js>/ui/widgets/codemirror/addon/hint/html-hint.js</js>
		<js>/ui/widgets/codemirror/addon/hint/xml-hint.js</js>
		<js>/ui/widgets/codemirror/addon/hint/javascript-hint.js</js>
		<css>/ui/widgets/codemirror/addon/hint/show-hint.css</css>
		<js>/ui/widgets/codemirror/addon/selection/active-line.js</js>
		<js>/ui/widgets/hanweb/codeedit/codeedit.js</js>
		<css>/ui/widgets/hanweb/codeedit/css/codeedit.css</css>
	</component>
	<component id="placeholder">
		<js>/ui/widgets/hanweb/placeholder/placeholder.js</js>
		<css>/ui/widgets/hanweb/placeholder/css/placeholder.css</css>
	</component>
	<component id="scroll">
		<js>/ui/widgets/scrollto/jquery.scrollTo.js</js>
	</component>
	<component id="simple_editor">
		<js>/ui/widgets/kindeditor/kindeditor-all-min.js</js>
		<css>/ui/widgets/kindeditor/themes/default/default.css</css>
		<js>/ui/widgets/hanweb/kindeditor/kindeditor.js</js>
	</component>
	<!-- ****************************************************************************************************** -->
	<component id="front_global">
		<css>/ui/front/css/global.css</css>
		<js>/ui/lib/jquery/jquery.min.js</js>
		<js>/ui/lib/jquery/jquery-migrate-1.4.1.min.js</js>
		<js>/ui/front/script/ui.js</js>
	</component>
	<component id="front_validity">
		<js>/ui/front/validity/validity.js</js>
		<css>/ui/front/validity/css/validity.css</css>
	</component>
	<component id="front_dialog">
		<css>/ui/widgets/dialog/skin/default/layer.css</css>
		<js>/ui/widgets/dialog/layer.js</js>
		<css>/ui/front/dialog/css/dialog.css</css>
		<js>/ui/front/dialog/dialog.js</js>
	</component>
	<component id="front_message">
		<css>/ui/front/msg/css/message.css</css>
		<js>/ui/front/msg/message.js</js>
		<dependencies>front_dialog</dependencies>
	</component>
	<component id="front_grid">
		<css>/ui/widgets/paging/paging.css</css>
		<js>/ui/widgets/paging/query.js</js>
		<js>/ui/widgets/paging/paging.js</js>
